### ISSUE TITLE
How to handle branches for LDAS?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA_env#15]
This is mainly a policy thread for @tclune to comment on, but I need his advice/expertise/opinion.

@weiyuan-jiang and @JustinPerket would like a branch and tag of ESMA_env where the MPI stack is Open MPI because that gives them better performance. This is fine, but the question I have is: What should we call this branch and tag?

For the branch, I'm thinking something like `ifort-openmpi` might be best for the branch as it seems to define the reason for it (compiler-MPI)? But maybe this is too much/not enough. It's not like it needs to be `dev/ldas` since it's a change in MPI stack more than anything LDAS specific.

As for the tag, hmm. I'm not sure. `v1.3.0` is what we have for master currently, so would this be `v1.3.0+openmpi3.1.1` or something like that? I'm not sure what the correct semver way to refer to something that is essentially identical to the original save for a change in an MPI stack? I don't want to call it `v1.3.1` as that would mean it's newer and frankly, I don't think it is. And I'd prefer not to put LDAS, say, in the tag.

Advice please @tclune.

**Comment by mathomp4** [comment]
Also note that it's possible we'd need something long-lived as if we go to Intel 18.0.5 well then I'd want to provide an Intel 18.0.5 Open MPI environment to LDAS with `ifort-openmpi`. So should I instead do something like `baselib-compiler-mpi-python` as the branch name to be completist?
```
5.1.7-ifort18.0.3-openmpi3.1.1-sivopyd
```
??

**Comment by weiyuan-jiang** [comment]
It is better for us to have a branch without GEOSldas's name in it, so it can be used by other fixtures and GEOSldas group don't have to maintain it.
