### ISSUE TITLE
build.csh ignores qos option

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/ESMA_env#18]
Very minor, but q/qos option is being ignored, and build will submit to debug regardless of another queue specified.

 As is, it appears like `$queue` here:

https://github.com/GEOS-ESM/ESMA_env/blob/9aaa2c1c9ca8821a1dae59da1a57bab1584570c0/build.csh#L531

Is being ignored in favor of this qos argument:
https://github.com/GEOS-ESM/ESMA_env/blob/9aaa2c1c9ca8821a1dae59da1a57bab1584570c0/build.csh#L538

**Comment by mathomp4** [comment]
@JustinPerket Yeah, this has always annoyed me. I'll have a fix for this (and #20) soon for testing.

**Comment by mathomp4** [comment]
@JustinPerket Can you please try out branch `feature/mathomp4/#18-#20-fixqueue-and-add-dirs`? I've fixed `-q` and added a new `-partition` option so that one can use a queue not in the `compute` partition.

**Comment by JustinPerket** [comment]
> @JustinPerket Can you please try out branch `feature/mathomp4/#18-#20-fixqueue-and-add-dirs`? I've fixed `-q` and added a new `-partition` option so that one can use a queue not in the `compute` partition.

Tested for functionality. looks great, thanks!
