### ISSUE TITLE
Can g5_modules handle two OSs?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/ESMA_env#31]
Per queries from @weiyuan-jiang and @gmao-rreichle, can we make a single `g5_modules` that can handle the SLES11/SLES12 mixed environment. 

The main issue is that `g5_modules` is both a script and a "sourced" file which is annoying at times. It will take some gymnastics to do this if possible.

**Comment by gmao-rreichle** [comment]
Matt,
I'm not sure I understand all of this correctly, but I don't think we would need a single g5_modules file that can switch between SLES12 and SLES11.  Rather, we just need an ESMA_env tag that we can point to from GEOSldas Externals.cfg that will work with SLES12.  In CVS, we would simply use two different revision numbers for g5_modules in our SLES11 and SLES12 tags.
- Rolf

**Comment by mathomp4** [comment]
I can do that, I was just hoping to make life easy for *me* since once SLES 12 becomes more popular, it would make my life easier if I didn't have to tell people to do:
```
mepo init
mepo clone
mepo checkout v2.0.0+sles12 ESMA_env
```
before they build if they are on SLES12, etc. Not a big burden, but it would be nice if `g5_modules` can handle both. I don't think it's impossible, but SLES12 has proven me wrong before.

Still, I can work on getting a SLES12 `g5_modules` with a release. I can't exactly use what @weiyuan-jiang has because it's updated the Intel compiler. To do an official release we'd need to carefully validate GEOS. I know that SLES12 has Intel 18.0.5, so I'd probably base any `v2.0.0+sles12` equivalent on that. Moving straight to Intel 20 might be a bridge too far for upstairs.

Note also that @weiyuan-jiang or you are free to tag what ever you want. It won't get an official release, but you can tag Weiyuan's commit for your purposes.

**Comment by gmao-rreichle** [comment]
@mathomp4 :  Whatever works for you should be ok for us.  My understanding, though, was that it would be preferable **not** to create our own tags for ESMA_env and rather point to an official release.

**Comment by mathomp4** [comment]
@gmao-rreichle @weiyuan-jiang I still want to try to get an "all-in-one" `g5_modules` but for now, I've made a release `v2.0.0+sles12` that is as close to `v2.0.0` as I can get. My guess is it is probably zero-diff and will be accepted, but I've marked it as "Pre-release" to be extra careful.
